### ISSUE TITLE
Error: Cannot find module 'Discord.js'

### ISSUE THREAD

**Issue by vadapadix** [mirko93s/Chill#8]
![image](https://user-images.githubusercontent.com/78354559/158378801-5775c0aa-a02b-4232-ac70-87f644a21dd6.png)
i run `npm i` and discord.js was installed
if i run `npm i Discord.js` and see error 404

**Comment by mirko93s** [comment]
it's `npm i discord.js`, lowercase...

**Comment by vadapadix** [comment]
> 

still the same error

**Comment by mirko93s** [comment]
my bad emojifind was requiring Discord.js instead discord.js
change it to be lowercase, i'll update the repo right now anyway, let me know if that fixes the issue

**Comment by vadapadix** [comment]
![изображение](https://user-images.githubusercontent.com/78354559/158390169-5d2ea1d2-8054-41a6-8561-17f8fdedcce9.png)
error fixed, but i have new error :/

**Comment by mirko93s** [comment]
Yeah I fixed that but I didn't update the code to github yet. It is caused by the `./commands` folder removed after I converted and moved all the commands to `./slashs`... You can just create a `commands` folder in the main directory to fix this, bot has still a command handler for "old message commands" (the ones executed in chat using prefix), but there isn't any message command at the moment. I just use them for debug, but maybe someone is still interested in using them so I left the command handler in the code.

**Comment by vadapadix** [comment]
ok, i just add a folder `commands` and now bot work!
thx!

**Comment by mirko93s** [comment]
you are welcome, thank you for reporting those!
